### ISSUE TITLE
crash while generating wad card

### ISSUE THREAD

**Issue by guigur** [guigur/longduzbot#28]
```
04/10/2024 09:58:37 sheevazia>Eco] Error generating the topwad card
04/10/2024 09:59:08 sheevazia>Eco] !wad
04/10/2024 09:59:08 server>Database] Request:  SELECT * FROM money WHERE userID=xxx AND guildID=xxx ORDER BY moneyID DESC LIMIT 1
04/10/2024 09:59:08 server>Database] Request OK
04/10/2024 09:59:08 server>Database] Request:  SELECT * FROM money WHERE userID=xxx AND guildID=xxx ORDER BY moneyID DESC LIMIT 1
04/10/2024 09:59:08 server>Database] Request OK
Ignoring exception in command wad:
Traceback (most recent call last):
  File "/home/guigur/.local/lib/python3.11/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guigur/bot/longduzbot/LongDuZbot/Eco.py", line 118, in wad
    card = certif.generateMoneyCard(userS, ggr_utilities.serverIcon(ctx.guild))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guigur/bot/longduzbot/LongDuZbot/certif.py", line 289, in generateMoneyCard
    genRoundImg(profile)
  File "/home/guigur/bot/longduzbot/LongDuZbot/certif.py", line 34, in genRoundImg
    mask = mask.resize(source.size, Image.ANTIALIAS)
                                    ^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/guigur/.local/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 902, in invoke
    await ctx.command.invoke(ctx)
  File "/home/guigur/.local/lib/python3.11/site-packages/discord/ext/commands/core.py", line 864, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/guigur/.local/lib/python3.11/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
I am being unloaded!
I am being unloaded!
I am being unloaded!
Exception ignored in: <module 'threading' from '/usr/lib/python3.11/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1583, in _shutdown
    lock.acquire()
KeyboardInterrupt:
```

**Comment by guigur** [comment]
fixed in release 1.5.1
